Document: eulisp
Title: Debian eulisp Manual
Author: <insert document author here>
Abstract: This manual describes what eulisp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/eulisp/eulisp.sgml.gz

Format: postscript
Files: /usr/share/doc/eulisp/eulisp.ps.gz

Format: text
Files: /usr/share/doc/eulisp/eulisp.text.gz

Format: HTML
Index: /usr/share/doc/eulisp/html/index.html
Files: /usr/share/doc/eulisp/html/*.html
